server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files  / /index.html;
    }
    location /api/ {
        proxy_pass https://inmotion-backend-production.up.railway.app/api/;
        proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
    }
}
